version: '1.0'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend
    hostname: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - farm-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    hostname: backend
    ports:
      - '3000:3000'
      # - '3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - farm-network

# network 정의
networks:
  farm-network:
    driver: bridge
